### PR TITLE
Fix twitch.js

### LINKED ISSUE #14: Unexpected token < in JSON at position 0
image

### PR DESCRIPTION
**Pull request by RisedSky**
This fix the issue #14
(https://github.com/Stateford/twitch-api/issues/14)

### CODE REVIEW

File: src/twitch.js [hunk 1]
```diff
@@ -47,6 +47,9 @@ Twitch.prototype.getUserId = function(username) {
         this.makeRequest(url)
             .then(data => {
                 let json = JSON.parse(data);
+                if (json.users[0] == null || json.users[0]._id == null) {
```
Comment (Stateford) [inline src/twitch.js:50]: Should this be a === comparator?

**Review by Stateford — APPROVED** [review]

File: src/twitch.js (hunk 1 above)
Comment (RisedSky) [reply src/twitch.js:50]: yeah my bad
```suggestion
                if (json.users[0] === null || json.users[0]._id === null) {
```
